//TOP PRIORITY
//USE FUNCTION TO RANDOMLY GENERATE GOAL NUMBER AND 4 CRYSTAL VALUES
//USE ONCLICK FUNCTION TO MAKE CRYSTAL VALUE ADD TOWARDS TOTAL
//USE ADDITION FUNCTION TO MAKE IT ADD UP
//ATTRIBUTE ADDED NUMEBERS TO BLANK SPACE
//WRITE IF ELSE STATEMENT FOR SCORE. IF = WIN, ELSE IF GN < SN = LOSS, OR IF GN > SN, KEEP PLAYING
//IF SCORES=== WIN, +1 TO WIN VAR
//ELSE +1 TO LOSE VAR
//
//
//
//
//
//
//
//
//
//